import { defineConfig } from "wxt";

// The MV3 manifest is generated by WXT into .output/<target>/manifest.json —
// there is no committed manifest.json.
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  manifest: ({ browser, command }) => {
    const isFirefox = browser === "firefox";
    // The web sign-in page posts the device token back via
    // chrome.runtime.sendMessage; only these origins may. localhost is dev-only
    // (`command === "serve"`) — shipping http://localhost/* in a published build
    // would let any localhost page reach the external-message surface.
    const matches =
      command === "serve"
        ? ["https://captureflow.xyz/*", "http://localhost/*"]
        : ["https://captureflow.xyz/*"];
    return {
      name: "CaptureFlow",
      description: "Record your screen and share an instant link.",
      // `offscreen` (where getDisplayMedia runs — no extra permission for the
      // capture itself) is Chromium-only, so gate it for Firefox. `scripting` +
      // `activeTab` inject the camera/mic permission iframe into the current tab
      // on demand (activeTab keeps it warning-free — no broad host access).
      permissions: isFirefox
        ? ["storage"]
        : ["storage", "offscreen", "scripting", "activeTab"],
      // Firefox MV3 lacks web→extension messaging, so omit it there.
      ...(isFirefox ? {} : { externally_connectable: { matches } }),
      // The injected iframe loads this extension page inside a web origin.
      ...(isFirefox
        ? {}
        : {
            web_accessible_resources: [
              { resources: ["permissions.html"], matches: ["<all_urls>"] },
            ],
          }),
    };
  },
});
