import { defineConfig } from "wxt";

// The MV3 manifest is generated by WXT into .output/<target>/manifest.json —
// there is no committed manifest.json.
export default defineConfig({
  modules: ["@wxt-dev/module-react"],
  manifest: ({ browser }) => ({
    name: "CaptureFlow",
    description: "Record your screen and share an instant link.",
    // `identity` drives sign-in via launchWebAuthFlow. `offscreen` (where
    // getDisplayMedia runs — no extra permission for capture itself) is
    // Chromium-only, so gate it for Firefox.
    permissions:
      browser === "firefox"
        ? ["storage", "identity"]
        : ["storage", "offscreen", "identity"],
  }),
});
